---
title: "Organização de dados biológicos"
---

Olá, este é o repositório contendo o material de apoio para o curso ministrado por mim, [Gabriel Nakamura](https://dimensionsofbiodiversity.weebly.com/), no PPG Ecologia da Universidade Federal do Rio Grande do Sul, onde atualmente sou pós-doc no [Laboratório de Ecologia Filogenética e Funcional](https://www.ufrgs.br/leff/). Trabalho com ecologia teórica, mais especificamente no desenvolvimento de métodos quantitativos nas áreas de ecologia de comunidades e macroevolução. Resolvi oferecer este curso por dois motivos, o primeiro por saber o quão penoso era (e ainda é em alguns momentos) organizar conjuntos de dados, análises, documentos e figuras em meu computador, de uma forma que, ao passar uma semana sem olhar para aquela pasta, eu não gastasse mais uma semana inteira tentando desvendar o que cada arquivo quer dizer. O segundo, para tentar ajudar os estudantes/pesquisadores a não sentirem a mesma aflição que a minha descrita anteriormente. A terceira (eram duas mas me lembrei de mais uma), para que possamos compreender o quão importante, apesar de muitas vezes negligenciado, é a reprodutibilidade para o processo de investigação científica.

Esta é a primeira edição deste curso, espero que ele possa ser útil e que durante esta semana nós possamos trocar conhecimentos.

Quase todo o material que está nesse sítio foi inspirado em outros materiais que tratam desses temas de uma maneira muito mais aprofundada do que a tratada aqui. O que tentei fazer foi reunir pontos que considero básicos para um curso de organização de dados e reprodutibilidade, de tal forma que quem usar esse material consiga realizar os procedimentos básicos sem que o dores sejam maiores que os ganhos. Aqueles que buscam se aprofundar nesse tópico devem buscar cada uma das referências que cito no fim desse texto.

Por último, espero que esse material nos ajude a lembrar que uma das bases do processo de descoberta científica é sua capacidade de reprodução, e que quando perdemos ela nos distanciamos muito do processo de fazer ciência. Que isso sirva de estímulo para que tornemos nossas pesquisas cada vez mais passíveis de reprodução por outras pessoas

Gabriel Nakamura