---
title: "Comandos básicos do Git"
author: "Gabriel Nakamura"
date: "5/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Em cima, em baixo, *Push* e vai

Modifica, salva, faz commit, faz pull, faz push e voilá, está completo o ciclo básico de operações necessárias para o controle de versão do seu projeto. Apesar de ter nomes próprios dentro do mundo do versionamento, fazemos essas ações no nosso dia-a-dia. A diferença é que o Git nos permite um versionamento muito mais sistematizado e organizado. Cada vez que um arquivo dentro de uma pasta observada pelo Git é modificada ele irá aparecer na aba *Git* do seu RStudio. Esse arquivo precisa ser "stagged", para que o *commit* possa ser feito, e então possamos fazer o *push*. Essa frase pode parecer estranha em um primeiro momento, mas traduzindo. Primeiro precisamos selecionar o arquivo (stage), nomear ele com uma indicação do que foi modificado em relação a versão anterior (commit) e então sincronizá-lo com o repositório remoto (push).

Todas essas funções podem ser feitas através do RStudio, mas também podemos fazer através da linha de comando (também com o RStudio através da aba *Terminal*).


**Em construção**

